USE [master]
GO

/****** Object:  Database [LaMejorCocina]    Script Date: 23/09/2020 11:14:47 p. m. ******/
CREATE DATABASE [LaMejorCocina]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LaMejorCocina', FILENAME = N'/var/opt/mssql/data/LaMejorCocina.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'LaMejorCocina_log', FILENAME = N'/var/opt/mssql/data/LaMejorCocina_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LaMejorCocina].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LaMejorCocina] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LaMejorCocina] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LaMejorCocina] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LaMejorCocina] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LaMejorCocina] SET ARITHABORT OFF 
GO

ALTER DATABASE [LaMejorCocina] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LaMejorCocina] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LaMejorCocina] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LaMejorCocina] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LaMejorCocina] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LaMejorCocina] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LaMejorCocina] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LaMejorCocina] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LaMejorCocina] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LaMejorCocina] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LaMejorCocina] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LaMejorCocina] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LaMejorCocina] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LaMejorCocina] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LaMejorCocina] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LaMejorCocina] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LaMejorCocina] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LaMejorCocina] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LaMejorCocina] SET  MULTI_USER 
GO

ALTER DATABASE [LaMejorCocina] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LaMejorCocina] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LaMejorCocina] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LaMejorCocina] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LaMejorCocina] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LaMejorCocina] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LaMejorCocina] SET  READ_WRITE 
GO


