//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaMejorCocina.ObjetosNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdDetalleFactura { get; set; }
        public int IdFactura { get; set; }
        public int IdCocinero { get; set; }
        public string Plato { get; set; }
        public string Importe { get; set; }
    
        public virtual Cocinero Cocinero { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
