//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaMejorCocina.ObjetosNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetallesFactura = new HashSet<DetalleFactura>();
        }
    
        public int IdFactura { get; set; }
        public int IdCliente { get; set; }
        public int IdCamarero { get; set; }
        public int IdMesa { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Total { get; set; }
    
        public virtual Camarero Camarero { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetallesFactura { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
